### ISSUE TITLE
KITTI training

### ISSUE THREAD

**Issue by geothan** [mit-han-lab/pvcnn#30]
I installed all the required dependencies, plus ninja in Ubuntu 18.04 in my conda enviroment, using the commands:

`pip install -r requirements.txt 
`
` conda install -c conda-forge ninja`

 But i get the error "subprocess.CalledProcessError: Command '['which', 'c++']' returned non-zero exit status 1." during training, has anyone faced this error?

i tried the following command:

`python train.py configs/kitti/frustum/pvcnne.py --devices 0,1
`
and i got:

`(pvcnn_env) george@inspiron:~/pvcnn$ python train.py configs/kitti/frustum/pvcnne.py --devices 0,1
==> loading configs from ['configs/kitti/frustum/pvcnne.py']
Traceback (most recent call last):
  File "train.py", line 266, in <module>
    main()
  File "train.py", line 79, in main
    configs = prepare()
  File "train.py", line 24, in prepare
    configs.update_from_modules(*args.configs)
  File "/home/george/pvcnn/utils/config.py", line 113, in update_from_modules
    importlib.import_module(module)
  File "/home/george/anaconda3/envs/pvcnn_env/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/george/pvcnn/configs/kitti/frustum/__init__.py", line 7, in <module>
    from meters.kitti import MeterFrustumKitti
  File "/home/george/pvcnn/meters/kitti/__init__.py", line 1, in <module>
    from meters.kitti.frustum import MeterFrustumKitti
  File "/home/george/pvcnn/meters/kitti/frustum.py", line 4, in <module>
    from modules.frustum import get_box_corners_3d
  File "/home/george/pvcnn/modules/__init__.py", line 1, in <module>
    from modules.ball_query import BallQuery
  File "/home/george/pvcnn/modules/ball_query.py", line 4, in <module>
    import modules.functional as F
  File "/home/george/pvcnn/modules/functional/__init__.py", line 1, in <module>
    from modules.functional.ball_query import ball_query
  File "/home/george/pvcnn/modules/functional/ball_query.py", line 3, in <module>
    from modules.functional.backend import _backend
  File "/home/george/pvcnn/modules/functional/backend.py", line 6, in <module>
    _backend = load(name='_pvcnn_backend',
  File "/home/george/anaconda3/envs/pvcnn_env/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 911, in load
    return _jit_compile(
  File "/home/george/anaconda3/envs/pvcnn_env/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1100, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/home/george/anaconda3/envs/pvcnn_env/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1181, in _write_ninja_file_and_build_library
    check_compiler_abi_compatibility(compiler)
  File "/home/george/anaconda3/envs/pvcnn_env/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 216, in check_compiler_abi_compatibility
    if not check_compiler_ok_for_platform(compiler):
  File "/home/george/anaconda3/envs/pvcnn_env/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 192, in check_compiler_ok_for_platform
    which = subprocess.check_output(['which', compiler], stderr=subprocess.STDOUT)
  File "/home/george/anaconda3/envs/pvcnn_env/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/george/anaconda3/envs/pvcnn_env/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['which', 'c++']' returned non-zero exit status 1.
`

**Comment by synxlin** [comment]
Hi, @geothan.
What's the result of running the command `which c++`?
Please try install build-essential: `sudo apt install build-essential`.

**Comment by geothan** [comment]
Now i faced another problem regarding cuda, should i use a specific version? I have installed the last version of Nvidia driver through Ubuntu repository.

i tried:

`python train.py configs/kitti/frustum/pvcnne.py --devices 0,1`

and i got:

`(pvcnn_env) george@inspiron:~/pvcnn$ python train.py configs/kitti/frustum/pvcnne.py --devices 0,1
==> loading configs from ['configs/kitti/frustum/pvcnne.py']
No CUDA runtime is found, using CUDA_HOME='/usr'
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=47 error=100 : no CUDA-capable device is detected
Traceback (most recent call last):
  File "train.py", line 266, in <module>
    main()
  File "train.py", line 79, in main
    configs = prepare()
  File "train.py", line 24, in prepare
    configs.update_from_modules(*args.configs)
  File "/home/george/pvcnn/utils/config.py", line 113, in update_from_modules
    importlib.import_module(module)
  File "/home/george/anaconda3/envs/pvcnn_env/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/george/pvcnn/configs/kitti/frustum/__init__.py", line 7, in <module>
    from meters.kitti import MeterFrustumKitti
  File "/home/george/pvcnn/meters/kitti/__init__.py", line 1, in <module>
    from meters.kitti.frustum import MeterFrustumKitti
  File "/home/george/pvcnn/meters/kitti/frustum.py", line 4, in <module>
    from modules.frustum import get_box_corners_3d
  File "/home/george/pvcnn/modules/__init__.py", line 1, in <module>
    from modules.ball_query import BallQuery
  File "/home/george/pvcnn/modules/ball_query.py", line 4, in <module>
    import modules.functional as F
  File "/home/george/pvcnn/modules/functional/__init__.py", line 1, in <module>
    from modules.functional.ball_query import ball_query
  File "/home/george/pvcnn/modules/functional/ball_query.py", line 3, in <module>
    from modules.functional.backend import _backend
  File "/home/george/pvcnn/modules/functional/backend.py", line 6, in <module>
    _backend = load(name='_pvcnn_backend',
  File "/home/george/anaconda3/envs/pvcnn_env/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 911, in load
    return _jit_compile(
  File "/home/george/anaconda3/envs/pvcnn_env/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1100, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/home/george/anaconda3/envs/pvcnn_env/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1194, in _write_ninja_file_and_build_library
    _write_ninja_file_to_build_library(
  File "/home/george/anaconda3/envs/pvcnn_env/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1492, in _write_ninja_file_to_build_library
    cuda_flags = common_cflags + COMMON_NVCC_FLAGS + _get_cuda_arch_flags()
  File "/home/george/anaconda3/envs/pvcnn_env/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1325, in _get_cuda_arch_flags
    capability = torch.cuda.get_device_capability()
  File "/home/george/anaconda3/envs/pvcnn_env/lib/python3.8/site-packages/torch/cuda/__init__.py", line 273, in get_device_capability
    prop = get_device_properties(device)
  File "/home/george/anaconda3/envs/pvcnn_env/lib/python3.8/site-packages/torch/cuda/__init__.py", line 278, in get_device_properties
    _lazy_init()  # will define _get_device_properties and _CudaDeviceProperties
  File "/home/george/anaconda3/envs/pvcnn_env/lib/python3.8/site-packages/torch/cuda/__init__.py", line 153, in _lazy_init
    torch._C._cuda_init()
RuntimeError: cuda runtime error (100) : no CUDA-capable device is detected at /pytorch/aten/src/THC/THCGeneral.cpp:47`

**Comment by zhijian-liu** [comment]
I'm closing this issue due to inactivity. Please feel free to reopen it if the problem has not been resolved.
