### ISSUE TITLE
ImportError: No module named '_pvcnn_backend'

### ISSUE THREAD

**Issue by SupriyaB1** [mit-han-lab/pvcnn#33]
ros@rosmachine:~/Downloads/pvcnn$ python3 train.py configs/kitti/frustum/pvcnne.py --devices 0 --evaluate --configs.evaluate.best_checkpoint_path /home/ros/Downloads/kitti.frustum.pvcnne.pth.tar --configs.evaluate.num_tests 20
==> loading configs from ['configs/kitti/frustum/pvcnne.py']
Traceback (most recent call last):
  File "train.py", line 266, in <module>
    main()
  File "train.py", line 79, in main
    configs = prepare()
  File "train.py", line 24, in prepare
    configs.update_from_modules(*args.configs)
  File "/home/ros/Downloads/pvcnn/utils/config.py", line 113, in update_from_modules
    importlib.import_module(module)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ros/Downloads/pvcnn/configs/kitti/frustum/__init__.py", line 7, in <module>
    from meters.kitti import MeterFrustumKitti
  File "/home/ros/Downloads/pvcnn/meters/kitti/__init__.py", line 1, in <module>
    from meters.kitti.frustum import MeterFrustumKitti
  File "/home/ros/Downloads/pvcnn/meters/kitti/frustum.py", line 4, in <module>
    from modules.frustum import get_box_corners_3d
  File "/home/ros/Downloads/pvcnn/modules/__init__.py", line 1, in <module>
    from modules.ball_query import BallQuery
  File "/home/ros/Downloads/pvcnn/modules/ball_query.py", line 4, in <module>
    import modules.functional as F
  File "/home/ros/Downloads/pvcnn/modules/functional/__init__.py", line 1, in <module>
    from modules.functional.ball_query import ball_query
  File "/home/ros/Downloads/pvcnn/modules/functional/ball_query.py", line 3, in <module>
    from modules.functional.backend import _backend
  File "/home/ros/Downloads/pvcnn/modules/functional/backend.py", line 8, in <module>
    sources=[os.path.join(_src_path,'src', f) for f in [
  File "/home/ros/.local/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 898, in load
    is_python_module)
  File "/home/ros/.local/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1097, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/home/ros/.local/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1418, in _import_module_from_library
    file, path, description = imp.find_module(module_name, [path])
  File "/usr/lib/python3.7/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pvcnn_backend'
 
Facing this issue while trying to do inference ,can anyone help me to solve this issue.

**Comment by zhijian-liu** [comment]
I'm not sure whether the issue is related to ROS. Could you try the installation on a normal machine?

**Comment by zhijian-liu** [comment]
I'm closing this issue due to inactivity. Please feel free to reopen it if the problem has not been resolved.

**Comment by Stone-sy** [comment]
I also encountered the same problem. How should I solve it?

`(pvcnn) root@stoneyshi-LC0:~/mycode/pvcnn$ python train.py configs/s3dis/pvcnn/area5.py --devices 0,1 --evaluate --configs.evaluate.best_checkpoint_path s3dis.pvcnn.area5.c1.pth.tar
==> loading configs from ['configs/s3dis/pvcnn/area5.py']
Traceback (most recent call last):
  File "train.py", line 266, in <module>
    main()
  File "train.py", line 79, in main
    configs = prepare()
  File "train.py", line 24, in prepare
    configs.update_from_modules(*args.configs)
  File "/home/shiying/mycode/pvcnn/utils/config.py", line 113, in update_from_modules
    importlib.import_module(module)
  File "/home/shiying/anaconda3/envs/pvcnn/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/shiying/mycode/pvcnn/configs/s3dis/pvcnn/__init__.py", line 3, in <module>
    from models.s3dis import PVCNN
  File "/home/shiying/mycode/pvcnn/models/s3dis/__init__.py", line 1, in <module>
    from models.s3dis.pointnet import PointNet
  File "/home/shiying/mycode/pvcnn/models/s3dis/pointnet.py", line 4, in <module>
    from models.utils import create_pointnet_components, create_mlp_components
  File "/home/shiying/mycode/pvcnn/models/utils.py", line 5, in <module>
    from modules import SharedMLP, PVConv, PointNetSAModule, PointNetAModule, PointNetFPModule
  File "/home/shiying/mycode/pvcnn/modules/__init__.py", line 1, in <module>
    from modules.ball_query import BallQuery
  File "/home/shiying/mycode/pvcnn/modules/ball_query.py", line 4, in <module>
    import modules.functional as F
  File "/home/shiying/mycode/pvcnn/modules/functional/__init__.py", line 1, in <module>
    from modules.functional.ball_query import ball_query
  File "/home/shiying/mycode/pvcnn/modules/functional/ball_query.py", line 3, in <module>
    from modules.functional.backend import _backend
  File "/home/shiying/mycode/pvcnn/modules/functional/backend.py", line 8, in <module>
    sources=[os.path.join(_src_path,'src', f) for f in [
  File "/home/shiying/anaconda3/envs/pvcnn/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 997, in load
    keep_intermediates=keep_intermediates)
  File "/home/shiying/anaconda3/envs/pvcnn/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1213, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/home/shiying/anaconda3/envs/pvcnn/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1560, in _import_module_from_library
    file, path, description = imp.find_module(module_name, [path])
  File "/home/shiying/anaconda3/envs/pvcnn/lib/python3.7/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pvcnn_backend'`

**Comment by zhijian-liu** [comment]
Could you please try to add `verbose=True` to https://github.com/mit-han-lab/pvcnn/blob/master/modules/functional/backend.py#L6, which should give you more detailed logging information?
