### ISSUE TITLE
IndexError while trying to use the BallQuery module

### ISSUE THREAD

**Issue by sandeepnmenon** [mit-han-lab/pvcnn#55]
I am trying to use the BallQuery module for my nearest neighbor call in my pointnet implementation.
Here is a snippet to reproduce the error.
```
from modules.ball_query import BallQuery
import numpy as np
import torch
_radius = 1
_num_neighbors = 1000
include_coordinates = True

ball_query = BallQuery(radius=_radius, num_neighbors=_num_neighbors, include_coordinates=include_coordinates)

coords = torch.tensor(np.array([[0,0,0], [1,1,1]])).cuda().float()
centers_coords = torch.tensor(np.array([[0.5,0,0], [0.5,1,1]])).cuda().float()
features = torch.tensor(np.array([[1,1,1,1], [0,1,1,0]])).cuda()
group = ball_query(coords, centers_coords, features)

print(group)
```

I am getting the following error

<details>
<summary>Traceback</summary>

```
Traceback (most recent call last):
  File "test_ball_query.py", line 13, in <module>
    group = ball_query(coords, centers_coords, features)
  File "/home/menonsandu/point-cloud-segmentation/venv-spvnas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/menonsandu/point-cloud-segmentation/private-e3d/e3d_pcd/pvcnn/modules/ball_query.py", line 19, in forward
    neighbor_indices = F.ball_query(centers_coords, points_coords, self.radius, self.num_neighbors)
  File "/home/menonsandu/point-cloud-segmentation/private-e3d/e3d_pcd/pvcnn/modules/functional/ball_query.py", line 19, in ball_query
    return _backend.ball_query(centers_coords, points_coords, radius, num_neighbors)
IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)
```

</details>

Is there a limitation in the range of distance/coordinates in the implementation?
I was not able to find any such issue in the `ball_query_kernel`.

**Comment by zhijian-liu** [comment]
@synxlin and @kentangSJTU, could you please take a look at this when you have time? Thanks!

**Comment by zhijian-liu** [comment]
Sorry for the really late follow-up! This issue is due to the wrong input shape. The input arguments of `ball_query` need to be in the shape of `BxCxN`, where `B` is the batch size and `N` is the number of points.

**Comment by zhijian-liu** [comment]
A working example is as follows:
```
from modules.ball_query import BallQuery
import numpy as np
import torch

_radius = 1
_num_neighbors = 1000
include_coordinates = True

ball_query = BallQuery(radius=_radius, num_neighbors=_num_neighbors, include_coordinates=include_coordinates)

coords = torch.tensor(np.array([[0,0,0], [1,1,1]])).cuda().float()
centers_coords = torch.tensor(np.array([[0.5,0,0], [0.5,1,1]])).cuda().float()
features = torch.tensor(np.array([[1,1,1,1], [0,1,1,0]])).cuda().float()

coords = coords.transpose(0, 1).unsqueeze(0)
centers_coords = centers_coords.transpose(0, 1).unsqueeze(0)
features = features.transpose(0, 1).unsqueeze(0)

group = ball_query(coords, centers_coords, features)
print(group)
```

**Comment by sandeepnmenon** [comment]
Thank you @zhijian-liu .
Closing
