### ISSUE TITLE
voxelization part

### ISSUE THREAD

**Issue by JudgeLJX** [mit-han-lab/pvcnn#69]
Hi,

Thanks for your work.

If I only want to voxelize the S3DIS dataset and deal with the voxelized feature, is it suitable to use your code?

Many thanks.

Judge

**Comment by JudgeLJX** [comment]
And the output of the dataloader is data[9, num_points] = [x_in_block, y_in_block, z_in_block, r, g, b, x / x_room, y / y_room, z / z_room], what is the mean of the block here? And is all the x,y,z from one epoch belong to the same block?

**Comment by JudgeLJX** [comment]
And I met this error when I use the following command:
python train.py configs/s3dis/pvcnn/area5/c1.py --devices 0,1

==> loading configs from ['configs/s3dis/pvcnn/area5/c1.py']
Traceback (most recent call last):
  File "/home/judgel/anaconda3/envs/pvcnn2/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1667, in _run_ninja_build
    subprocess.run(
  File "/home/judgel/anaconda3/envs/pvcnn2/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train.py", line 268, in <module>
    main()
  File "train.py", line 79, in main
    configs = prepare()
  File "train.py", line 24, in prepare
    configs.update_from_modules(*args.configs)
  File "/home/judgel/Desktop/pvcnn-master/utils/config.py", line 113, in update_from_modules
    importlib.import_module(module)
  File "/home/judgel/anaconda3/envs/pvcnn2/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/judgel/Desktop/pvcnn-master/configs/s3dis/pvcnn/__init__.py", line 3, in <module>
    from models.s3dis import PVCNN
  File "/home/judgel/Desktop/pvcnn-master/models/s3dis/__init__.py", line 1, in <module>
    from models.s3dis.pointnet import PointNet
  File "/home/judgel/Desktop/pvcnn-master/models/s3dis/pointnet.py", line 4, in <module>
    from models.utils import create_pointnet_components, create_mlp_components
  File "/home/judgel/Desktop/pvcnn-master/models/utils.py", line 5, in <module>
    from modules import SharedMLP, PVConv, PointNetSAModule, PointNetAModule, PointNetFPModule
  File "/home/judgel/Desktop/pvcnn-master/modules/__init__.py", line 1, in <module>
    from modules.ball_query import BallQuery
  File "/home/judgel/Desktop/pvcnn-master/modules/ball_query.py", line 4, in <module>
    import modules.functional as F
  File "/home/judgel/Desktop/pvcnn-master/modules/functional/__init__.py", line 1, in <module>
    from modules.functional.ball_query import ball_query
  File "/home/judgel/Desktop/pvcnn-master/modules/functional/ball_query.py", line 3, in <module>
    from modules.functional.backend import _backend
  File "/home/judgel/Desktop/pvcnn-master/modules/functional/backend.py", line 6, in <module>
    _backend = load(name='_pvcnn_backend',
  File "/home/judgel/anaconda3/envs/pvcnn2/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1079, in load
    return _jit_compile(
  File "/home/judgel/anaconda3/envs/pvcnn2/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1292, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/home/judgel/anaconda3/envs/pvcnn2/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1404, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/home/judgel/anaconda3/envs/pvcnn2/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1683, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension '_pvcnn_backend': [1/7] /usr/bin/nvcc --generate-dependencies-with-compile --dependency-output ball_query.cuda.o.d -DTORCH_EXTENSION_NAME=_pvcnn_backend -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/judgel/anaconda3/envs/pvcnn2/lib/python3.8/site-packages/torch/include -isystem /home/judgel/anaconda3/envs/pvcnn2/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/judgel/anaconda3/envs/pvcnn2/lib/python3.8/site-packages/torch/include/TH -isystem /home/judgel/anaconda3/envs/pvcnn2/lib/python3.8/site-packages/torch/include/THC -isystem /home/judgel/anaconda3/envs/pvcnn2/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -std=c++14 -c /home/judgel/Desktop/pvcnn-master/modules/functional/src/ball_query/ball_query.cu -o ball_query.cuda.o 
FAILED: ball_query.cuda.o 
/usr/bin/nvcc --generate-dependencies-with-compile --dependency-output ball_query.cuda.o.d -DTORCH_EXTENSION_NAME=_pvcnn_backend -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/judgel/anaconda3/envs/pvcnn2/lib/python3.8/site-packages/torch/include -isystem /home/judgel/anaconda3/envs/pvcnn2/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/judgel/anaconda3/envs/pvcnn2/lib/python3.8/site-packages/torch/include/TH -isystem /home/judgel/anaconda3/envs/pvcnn2/lib/python3.8/site-packages/torch/include/THC -isystem /home/judgel/anaconda3/envs/pvcnn2/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -std=c++14 -c /home/judgel/Desktop/pvcnn-master/modules/functional/src/ball_query/ball_query.cu -o ball_query.cuda.o 
nvcc fatal   : Unknown option '-generate-dependencies-with-compile'
[2/7] /usr/bin/nvcc --generate-dependencies-with-compile --dependency-output grouping.cuda.o.d -DTORCH_EXTENSION_NAME=_pvcnn_backend -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/judgel/anaconda3/envs/pvcnn2/lib/python3.8/site-packages/torch/include -isystem /home/judgel/anaconda3/envs/pvcnn2/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/judgel/anaconda3/envs/pvcnn2/lib/python3.8/site-packages/torch/include/TH -isystem /home/judgel/anaconda3/envs/pvcnn2/lib/python3.8/site-packages/torch/include/THC -isystem /home/judgel/anaconda3/envs/pvcnn2/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -std=c++14 -c /home/judgel/Desktop/pvcnn-master/modules/functional/src/grouping/grouping.cu -o grouping.cuda.o 
FAILED: grouping.cuda.o 
/usr/bin/nvcc --generate-dependencies-with-compile --dependency-output grouping.cuda.o.d -DTORCH_EXTENSION_NAME=_pvcnn_backend -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/judgel/anaconda3/envs/pvcnn2/lib/python3.8/site-packages/torch/include -isystem /home/judgel/anaconda3/envs/pvcnn2/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/judgel/anaconda3/envs/pvcnn2/lib/python3.8/site-packages/torch/include/TH -isystem /home/judgel/anaconda3/envs/pvcnn2/lib/python3.8/site-packages/torch/include/THC -isystem /home/judgel/anaconda3/envs/pvcnn2/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -std=c++14 -c /home/judgel/Desktop/pvcnn-master/modules/functional/src/grouping/grouping.cu -o grouping.cuda.o 
nvcc fatal   : Unknown option '-generate-dependencies-with-compile'
[3/7] /usr/bin/nvcc --generate-dependencies-with-compile --dependency-output neighbor_interpolate.cuda.o.d -DTORCH_EXTENSION_NAME=_pvcnn_backend -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/judgel/anaconda3/envs/pvcnn2/lib/python3.8/site-packages/torch/include -isystem /home/judgel/anaconda3/envs/pvcnn2/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/judgel/anaconda3/envs/pvcnn2/lib/python3.8/site-packages/torch/include/TH -isystem /home/judgel/anaconda3/envs/pvcnn2/lib/python3.8/site-packages/torch/include/THC -isystem /home/judgel/anaconda3/envs/pvcnn2/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -std=c++14 -c /home/judgel/Desktop/pvcnn-master/modules/functional/src/interpolate/neighbor_interpolate.cu -o neighbor_interpolate.cuda.o 
FAILED: neighbor_interpolate.cuda.o 
/usr/bin/nvcc --generate-dependencies-with-compile --dependency-output neighbor_interpolate.cuda.o.d -DTORCH_EXTENSION_NAME=_pvcnn_backend -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/judgel/anaconda3/envs/pvcnn2/lib/python3.8/site-packages/torch/include -isystem /home/judgel/anaconda3/envs/pvcnn2/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/judgel/anaconda3/envs/pvcnn2/lib/python3.8/site-packages/torch/include/TH -isystem /home/judgel/anaconda3/envs/pvcnn2/lib/python3.8/site-packages/torch/include/THC -isystem /home/judgel/anaconda3/envs/pvcnn2/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -std=c++14 -c /home/judgel/Desktop/pvcnn-master/modules/functional/src/interpolate/neighbor_interpolate.cu -o neighbor_interpolate.cuda.o 
nvcc fatal   : Unknown option '-generate-dependencies-with-compile'
[4/7] /usr/bin/nvcc --generate-dependencies-with-compile --dependency-output trilinear_devox.cuda.o.d -DTORCH_EXTENSION_NAME=_pvcnn_backend -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/judgel/anaconda3/envs/pvcnn2/lib/python3.8/site-packages/torch/include -isystem /home/judgel/anaconda3/envs/pvcnn2/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/judgel/anaconda3/envs/pvcnn2/lib/python3.8/site-packages/torch/include/TH -isystem /home/judgel/anaconda3/envs/pvcnn2/lib/python3.8/site-packages/torch/include/THC -isystem /home/judgel/anaconda3/envs/pvcnn2/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -std=c++14 -c /home/judgel/Desktop/pvcnn-master/modules/functional/src/interpolate/trilinear_devox.cu -o trilinear_devox.cuda.o 
FAILED: trilinear_devox.cuda.o 
/usr/bin/nvcc --generate-dependencies-with-compile --dependency-output trilinear_devox.cuda.o.d -DTORCH_EXTENSION_NAME=_pvcnn_backend -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/judgel/anaconda3/envs/pvcnn2/lib/python3.8/site-packages/torch/include -isystem /home/judgel/anaconda3/envs/pvcnn2/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/judgel/anaconda3/envs/pvcnn2/lib/python3.8/site-packages/torch/include/TH -isystem /home/judgel/anaconda3/envs/pvcnn2/lib/python3.8/site-packages/torch/include/THC -isystem /home/judgel/anaconda3/envs/pvcnn2/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -std=c++14 -c /home/judgel/Desktop/pvcnn-master/modules/functional/src/interpolate/trilinear_devox.cu -o trilinear_devox.cuda.o 
nvcc fatal   : Unknown option '-generate-dependencies-with-compile'
[5/7] /usr/bin/nvcc --generate-dependencies-with-compile --dependency-output sampling.cuda.o.d -DTORCH_EXTENSION_NAME=_pvcnn_backend -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/judgel/anaconda3/envs/pvcnn2/lib/python3.8/site-packages/torch/include -isystem /home/judgel/anaconda3/envs/pvcnn2/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/judgel/anaconda3/envs/pvcnn2/lib/python3.8/site-packages/torch/include/TH -isystem /home/judgel/anaconda3/envs/pvcnn2/lib/python3.8/site-packages/torch/include/THC -isystem /home/judgel/anaconda3/envs/pvcnn2/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -std=c++14 -c /home/judgel/Desktop/pvcnn-master/modules/functional/src/sampling/sampling.cu -o sampling.cuda.o 
FAILED: sampling.cuda.o 
/usr/bin/nvcc --generate-dependencies-with-compile --dependency-output sampling.cuda.o.d -DTORCH_EXTENSION_NAME=_pvcnn_backend -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/judgel/anaconda3/envs/pvcnn2/lib/python3.8/site-packages/torch/include -isystem /home/judgel/anaconda3/envs/pvcnn2/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/judgel/anaconda3/envs/pvcnn2/lib/python3.8/site-packages/torch/include/TH -isystem /home/judgel/anaconda3/envs/pvcnn2/lib/python3.8/site-packages/torch/include/THC -isystem /home/judgel/anaconda3/envs/pvcnn2/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -std=c++14 -c /home/judgel/Desktop/pvcnn-master/modules/functional/src/sampling/sampling.cu -o sampling.cuda.o 
nvcc fatal   : Unknown option '-generate-dependencies-with-compile'
[6/7] /usr/bin/nvcc --generate-dependencies-with-compile --dependency-output vox.cuda.o.d -DTORCH_EXTENSION_NAME=_pvcnn_backend -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/judgel/anaconda3/envs/pvcnn2/lib/python3.8/site-packages/torch/include -isystem /home/judgel/anaconda3/envs/pvcnn2/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/judgel/anaconda3/envs/pvcnn2/lib/python3.8/site-packages/torch/include/TH -isystem /home/judgel/anaconda3/envs/pvcnn2/lib/python3.8/site-packages/torch/include/THC -isystem /home/judgel/anaconda3/envs/pvcnn2/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -std=c++14 -c /home/judgel/Desktop/pvcnn-master/modules/functional/src/voxelization/vox.cu -o vox.cuda.o 
FAILED: vox.cuda.o 
/usr/bin/nvcc --generate-dependencies-with-compile --dependency-output vox.cuda.o.d -DTORCH_EXTENSION_NAME=_pvcnn_backend -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/judgel/anaconda3/envs/pvcnn2/lib/python3.8/site-packages/torch/include -isystem /home/judgel/anaconda3/envs/pvcnn2/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/judgel/anaconda3/envs/pvcnn2/lib/python3.8/site-packages/torch/include/TH -isystem /home/judgel/anaconda3/envs/pvcnn2/lib/python3.8/site-packages/torch/include/THC -isystem /home/judgel/anaconda3/envs/pvcnn2/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -std=c++14 -c /home/judgel/Desktop/pvcnn-master/modules/functional/src/voxelization/vox.cu -o vox.cuda.o 
nvcc fatal   : Unknown option '-generate-dependencies-with-compile'
ninja: build stopped: subcommand failed.

Do you have any suggestion?

**Comment by zhijian-liu** [comment]
You could probably use TorchSparse for point cloud voxelization (using the `sparse_quantize` function).
