### ISSUE TITLE
About ModuleNotFoundError: No module named 'config.shapenet'

### ISSUE THREAD

**Issue by eine-kenta** [mit-han-lab/pvcnn#73]
Hi, it is wrong when i train the command:
`python train.py config/shapenet/pvcnn/c1.py`

And the error is like this:

```typescript
==> loading configs from ['config/shapenet/pvcnn/c1.py']
Traceback (most recent call last):
  File "train.py", line 266, in <module>
    main()
  File "train.py", line 79, in main
    configs = prepare()
  File "train.py", line 24, in prepare
    configs.update_from_modules(*args.configs)
  File "/workspace/pvcnn-master/utils/config.py", line 113, in update_from_modules
    importlib.import_module(module)
  File "/opt/conda/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'config.shapenet
```

**Comment by zhijian-liu** [comment]
It should be `python train.py configs/shapenet/pvcnn/c1.py` (with `configs` instead of `config`).
